version: '3.8'
services:
  app:
    container_name: geohub_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    container_name: geohub_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./geohub_db/mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
